import { Sparkles, Wand2, AudioLines, Video, Image as ImageIcon, FileText } from 'lucide-react';
import type { CSSProperties, ReactNode } from 'react';

/**
 * AIContentLabel — EU AI Act Article 50(4)
 * -------------------------------------------------------------
 * Marks AI-generated or AI-manipulated content (incl. deepfakes) as artificial,
 * in a visible AND machine-readable way. Article 50(4) has no transition period
 * for new content, so this is the most time-sensitive pattern in the kit.
 *
 * - Visible: a clear label a person can read.
 * - Machine-readable: a `data-ai-content` attribute other software can detect,
 *   plus an `aria-label` so assistive tech announces it.
 * - As an overlay on media, keeps AA contrast by sitting on an ink scrim.
 */
export type AIContentStatus = 'ai-generated' | 'ai-assisted' | 'ai-edited';
export type AIMediaType = 'image' | 'video' | 'audio' | 'text';
export type AIContentVariant = 'overlay' | 'caption';

export interface AIContentLabelProps {
  status?: AIContentStatus;
  mediaType?: AIMediaType;
  variant?: AIContentVariant;
  /** Optional extra detail, e.g. the tool or model used. */
  detail?: string;
  className?: string;
  style?: CSSProperties;
}

const STATUS_TEXT: Record<AIContentStatus, string> = {
  'ai-generated': 'AI-generated',
  'ai-assisted': 'AI-assisted',
  'ai-edited': 'AI-edited',
};

const STATUS_LONG: Record<AIContentStatus, string> = {
  'ai-generated': 'This content was generated by artificial intelligence.',
  'ai-assisted': 'This content was created with the assistance of artificial intelligence.',
  'ai-edited': 'This content was edited or manipulated using artificial intelligence.',
};

const MEDIA_ICON: Record<AIMediaType, ReactNode> = {
  image: <ImageIcon aria-hidden="true" size={14} strokeWidth={2.25} />,
  video: <Video aria-hidden="true" size={14} strokeWidth={2.25} />,
  audio: <AudioLines aria-hidden="true" size={14} strokeWidth={2.25} />,
  text: <FileText aria-hidden="true" size={14} strokeWidth={2.25} />,
};

export default function AIContentLabel({
  status = 'ai-generated',
  mediaType = 'image',
  variant = 'caption',
  detail,
  className = '',
  style,
}: AIContentLabelProps) {
  const text = STATUS_TEXT[status];
  const long = STATUS_LONG[status];
  const ariaLabel = detail ? `${long} ${detail}` : long;
  const icon = status === 'ai-edited' ? <Wand2 aria-hidden="true" size={14} strokeWidth={2.25} /> : <Sparkles aria-hidden="true" size={14} strokeWidth={2.5} />;

  if (variant === 'overlay') {
    return (
      <span
        role="img"
        data-ai-content={status}
        data-ai-media={mediaType}
        aria-label={ariaLabel}
        className={`pointer-events-none inline-flex items-center gap-1.5 rounded-md bg-ink/85 px-2 py-1 text-xs font-semibold text-paper backdrop-blur-sm ${className}`}
        style={style}
      >
        <span className="text-orange">{icon}</span>
        <span aria-hidden="true">{text}</span>
      </span>
    );
  }

  // caption (default) — sits beneath or beside the media
  return (
    <span
      role="img"
      data-ai-content={status}
      data-ai-media={mediaType}
      aria-label={ariaLabel}
      className={`inline-flex items-center gap-1.5 rounded-md border border-line bg-surface px-2 py-1 text-xs font-medium text-ink ${className}`}
      style={style}
    >
      <span className="text-orange">{icon}</span>
      <span className="text-muted" aria-hidden="true">
        {MEDIA_ICON[mediaType]}
      </span>
      <span aria-hidden="true">
        {text}
        {detail ? <span className="text-muted"> · {detail}</span> : null}
      </span>
    </span>
  );
}
